// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PucPocV1.Data;

#nullable disable

namespace PucPocV1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009222707_AdicionarAreasETecnologias")]
    partial class AdicionarAreasETecnologias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PucPocV1.Models.AreaConhecimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("AreaConhecimento");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nome = "Desenvolvimento Web"
                        },
                        new
                        {
                            ID = 2,
                            Nome = "Banco de Dados"
                        },
                        new
                        {
                            ID = 3,
                            Nome = "Desenvolvimento Mobile"
                        },
                        new
                        {
                            ID = 4,
                            Nome = "Inteligência Artificial"
                        },
                        new
                        {
                            ID = 5,
                            Nome = "Segurança da Informação"
                        });
                });

            modelBuilder.Entity("PucPocV1.Models.Mentor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Mentor");
                });

            modelBuilder.Entity("PucPocV1.Models.MentorAreaConhecimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_AreaConhecimento")
                        .HasColumnType("int");

                    b.Property<int>("ID_Mentor")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_AreaConhecimento");

                    b.HasIndex("ID_Mentor");

                    b.ToTable("MentorAreaConhecimento");
                });

            modelBuilder.Entity("PucPocV1.Models.MentorTecnologia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Mentor")
                        .HasColumnType("int");

                    b.Property<int>("ID_Tecnologia")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Mentor");

                    b.HasIndex("ID_Tecnologia");

                    b.ToTable("MentorTecnologia");
                });

            modelBuilder.Entity("PucPocV1.Models.Mentorado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Mentorado");
                });

            modelBuilder.Entity("PucPocV1.Models.Tecnologia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Tecnologia");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nome = "C#"
                        },
                        new
                        {
                            ID = 2,
                            Nome = "Java"
                        },
                        new
                        {
                            ID = 3,
                            Nome = "JavaScript"
                        },
                        new
                        {
                            ID = 4,
                            Nome = "Python"
                        },
                        new
                        {
                            ID = 5,
                            Nome = "SQL Server"
                        },
                        new
                        {
                            ID = 6,
                            Nome = "ASP.NET Core"
                        },
                        new
                        {
                            ID = 7,
                            Nome = "React"
                        });
                });

            modelBuilder.Entity("PucPocV1.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ativo_Area")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Nasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Escolaridade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("NivelAcesso")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PucPocV1.Models.Mentor", b =>
                {
                    b.HasOne("PucPocV1.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PucPocV1.Models.MentorAreaConhecimento", b =>
                {
                    b.HasOne("PucPocV1.Models.AreaConhecimento", "AreaConhecimento")
                        .WithMany()
                        .HasForeignKey("ID_AreaConhecimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PucPocV1.Models.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("ID_Mentor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaConhecimento");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("PucPocV1.Models.MentorTecnologia", b =>
                {
                    b.HasOne("PucPocV1.Models.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("ID_Mentor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PucPocV1.Models.Tecnologia", "Tecnologia")
                        .WithMany()
                        .HasForeignKey("ID_Tecnologia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Tecnologia");
                });

            modelBuilder.Entity("PucPocV1.Models.Mentorado", b =>
                {
                    b.HasOne("PucPocV1.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
